<template lang="html">
  <div>
    <el-form inline size="middle">
      <el-form-item>
        <el-input
          v-model="formData.appName"
          placeholder="馆名称"
          clearable>
        </el-input>
      </el-form-item>
      <el-form-item>
        <el-select
          v-model="formData.type"
          placeholder="设备类型"
          clearable>
          <el-option
            v-for="(i, j) in EquipTypeList"
            :key="j"
            :label="i.label"
            :value="i.value">
          </el-option>
        </el-select>
      </el-form-item>
      <el-form-item>
        <el-button
          type="primary"
          size="mini"
          @click="SearchApp">
          查询
        </el-button>
        <el-button
          type="primary"
          size="mini"
          @click="AddApp">
          新增馆
        </el-button>
      </el-form-item>
    </el-form>
    <el-table
      v-loading="tableData.loading"
      :data="tableData.DataList"
      :height="tableData.height"
      border
      fit>
      <el-table-column
        type="index"
        label="序号"
        width="60px">
      </el-table-column>
      <el-table-column
        label="馆名称"
        prop=""
        show-overflow-tooltip>
      </el-table-column>
      <el-table-column
        label="设备类型"
        prop=""
        show-overflow-tooltip>
      </el-table-column>
      <el-table-column
        label="整改单发送时间间隔"
        prop=""
        show-overflow-tooltip>
      </el-table-column>
      <el-table-column
        label="巡查-触发条件"
        prop=""
        show-overflow-tooltip>
      </el-table-column>
      <el-table-column label="操作" width="150px">
        <template slot-scope="scope">
          <el-button
            type="primary"
            size="mini"
            @click="EditApp(scope.row.Id)">
            修改
          </el-button>
          <el-button
            type="danger"
            size="mini"
            @click="DeleteApp(scope.row.Id)">
            删除
          </el-button>
        </template>
      </el-table-column>
    </el-table>
    <Pagination
      v-show="pages.total>0"
      :total="pages.total"
      :page.sync="pages.page"
      :pageSizes="pages.pageSizes"
      :limit.sync="pages.limit"
      @pagination="pageChange">
    </Pagination>
    <EditAppSet
      :EditAppSetShow="editAppSet.show"
      :EditAppSetData="editAppSet.data"
      @CloseEditAppSet="CloseEditAppSet">
    </EditAppSet>
  </div>

</template>
<script src="./ViolationTriggerSet.js"></script>
<style lang="css" scoped>
</style>
